version: 0.2
          phases:
            install:
              runtime-versions:
                python: 3.11
              commands:
                - pip install cfn-lint pyyaml boto3
            pre_build:
              commands:
                - echo "Validating CloudFormation templates..."
                - cfn-lint Hoth/FHIR/cloudformations/*.yml
            build:
              commands:
                - echo "Running Python unit tests..."
                - python -m pytest Hoth/FHIR/tests/ -v || true
                - echo "Validating Python syntax..."
                - python -m py_compile Hoth/FHIR/glue/*.py
                - python -m py_compile Hoth/FHIR/lambdas/*.py
            post_build:
              commands:
                - echo "Validation completed successfully"
          artifacts:
            files:
              - '**/*'