Resources:

  ArtifactBucket:
    Type: AWS::S3::Bucket

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: arn:aws:iam::123456789012:role/codepipeline-role
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucket
      Stages:

        - Name: Source
          Actions:
            - Name: GitHub
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: 1
              Configuration:
                ConnectionArn: arn:aws:codestar-connections:...
                FullRepositoryId: org/etl-repo
                BranchName: develop
              OutputArtifacts:
                - Name: SourceOutput

        - Name: Validate
          Actions:
            - Name: ValidateCode
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - Name: SourceOutput
              Configuration:
                ProjectName: etl-validate

        - Name: DeployDev
          Actions:
            - Name: CFNDeployDev
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: etl-dev-stack
                TemplatePath: SourceOutput::cloudformation/etl-stack.yaml
                ParameterOverrides: |
                  {
                    "Env": "dev",
                    "ArtifactBucket": "etl-artifacts-dev"
                  }

        - Name: Approval
          Actions:
            - Name: ManualApproval
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: Manual
                Version: 1

        - Name: DeployStg
          Actions:
            - Name: CFNDeployStg
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: etl-stg-stack
                TemplatePath: SourceOutput::cloudformation/etl-stack.yaml
                ParameterOverrides: |
                  {
                    "Env": "stg",
                    "ArtifactBucket": "etl-artifacts-stg"
                  }
