version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install aws-sam-cli
      - sam --version

  pre_build:
    commands:
      - echo "=== Pre-build phase ==="
      - echo "Validating SAM template..."
      - sam validate --template serverless-app-template.yml --lint

  build:
    commands:
      - echo "=== Build phase ==="
      - echo "Packaging SAM application..."
      - sam package --template-file serverless-app-template.yml --output-template-file packaged-template.yml --s3-bucket ${ARTIFACT_BUCKET} --s3-prefix sam-artifacts/${APPLICATION_NAME}/${ENVIRONMENT_NAME}
      
      - echo "Creating config.json..."
      - |
        cat > config.json << EOF
        {
          "Parameters": {
            "EnvironmentName": "${ENVIRONMENT_NAME}",
            "ApplicationName": "${APPLICATION_NAME}",
            "LogRetentionDays": "14"
          },
          "Tags": {
            "Environment": "${ENVIRONMENT_NAME}",
            "Application": "${APPLICATION_NAME}",
            "ManagedBy": "CloudFormation"
          }
        }
        EOF
      - cat config.json

  post_build:
    commands:
      - echo "=== Post-build phase ==="
      - echo "Uploading Glue script..."
      - |
        GLUE_BUCKET="${APPLICATION_NAME}-glue-data-$(aws sts get-caller-identity --query Account --output text)-${AWS_REGION}"
        if [ -f "glue/csv_processor.py" ]; then
          aws s3 cp glue/csv_processor.py s3://${GLUE_BUCKET}/scripts/csv_processor.py --region ${AWS_REGION} || echo "Bucket may not exist yet"
        fi
      - echo "Build completed!"

artifacts:
  files:
    - packaged-template.yml
    - config.json
  discard-paths: yes